### PR TITLE
Upgrade rabbitmq client

### PR DESCRIPTION
**Pull request by denkv**

### CODE REVIEW

**Review by MichaelRoeder — COMMENTED** [review]
Can you please make sure that the RabbitMQ broker used for testing has the same version? To me, it looks like it is still using the old broker for the junit tests.

**Comment by denkv** [comment]
We're upgrading only RabbitMQ Java client, not RabbitMQ itself.

We did not specify version of RabbitMQ used in tests. Since [Java client 4.x](https://github.com/rabbitmq/rabbitmq-java-client/#4x-series) is intended for use with RabbitMQ `3.x`, I've added that.

**Comment by MichaelRoeder** [comment]
Ok, got it. I thought they would keep the version number of the client library (at least similar) to the version of the RabbitMQ broker.

**Review by MichaelRoeder — APPROVED** [review]
LGTM

**Pull request merged**
